<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>IL2026;IL3050</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="analyzers\**" />
    <ProjectReference Include="..\chrome-devtools-cli\analyzers\DomainAnalyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" PrivateAssets="all" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.12.11" PrivateAssets="all" />
    <PackageReference Include="Meziantou.Analyzer" Version="2.0.186" PrivateAssets="all" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.6.0.109712" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <None Update="wwwroot\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
